### ISSUE TITLE
Using BayesAss in clusters

### ISSUE THREAD

**Issue by AriadneSabbag** [brannala/BA3#1]
Hi, Dr. Rannala!

I have been trying to install and compile BayesAss from Source Code (https://github.com/brannala/BA3/releases), to install in my personal Linux and/or a cluster that I use. I am very bad in computing, so I do things only by following manuals.

Following your manual, I can't find configure file, for example.

Is there anything that I might be downloading wrong?

Thank you very much.

**Comment by brannala** [comment]
Hi Ariadne,
The program originally used the automake build system but I 
decided to change to a simpler system and have not yet updated the 
manual (most people use one of the precompiled 
binaries). Therefore there is no longer a configure step when 
building the program. You should download the file:

https://github.com/brannala/BA3/archive/v3.04.tar.gz

unpack it and then type make in the root directory to compile the 
program. To succeed you will need to install the Gnu scientific 
library (gsl) on your machine first and then modify the Makefile 
to point to the correct library location. By default the file 
points to the library locations on my personal machine. Here are 
the Makefile contents: 

P = BA3
INCLUDE = -Iinclude -I/Users/bruce/gsl-2.2.1/gsl-2.2.1/
LIBS = -L/Users/bruce/gsl-2.2.1/gsl-2.2.1/libsX86_64 
CFLAGS = -Wall -O3
LDLIBS = -lgsl -lcblas
CC=g++
all:
	$(CC) $(CFLAGS) src/main.cpp $(INCLUDE) $(LIBS) $(LDLIBS) 
	-o BA3X86_64

You should edit the INCLUDE and LIBS statements to point to the 
correct places for your gsl installation. Also, change -lcblas to 
-lgslcblas on the LDLIBS line.

If you have trouble send me your Makefile and the compiler errors 
and I can have a look.
Bruce


Ariadne Fares Sabbag writes:

> Hi, Dr. Rannala!
>
> I have been trying to install and compile BayesAss from Source 
> Code (https://github.com/brannala/BA3/releases), to install in 
> my personal Linux and/or a cluster that I use. I am very bad in 
> computing, so I do things only by following manuals.
>
> Following your manual, I can't find configure file, for example.
>
> Is there anything that I might be downloading wrong?
>
> Thank you very much.


-- 
Bruce Rannala
Professor, Evolution & Ecology, UC Davis
