### ISSUE TITLE
checkDataSize counting missing data in allele count?

### ISSUE THREAD

**Issue by dorseyb** [brannala/BA3#11]
Hi Dr. Rannala,

BA3SNP is exiting with an error stating that a locus in my data has more than the maximum number of alleles. I filtered my data to max 4 alleles/locus and double checked that this is indeed the case for the locus in question. Looking at the checkDataSize function where it counts the number of alleles per locus, it looks like it would count a missing allele (i.e. '0') in the total allele count for a locus. I don't think it differentiates between allele labels (e.g. 01 or 03) and the missing data label: '0' when adding to the alleleLabels map variable.

I know nothing about coding in C++ so I may be wrong, but any help would be appreciated.

Thanks,
Brian D.

**Comment by brannala** [comment]
Hi Brian,
Thanks for identifying this bug, which has now been fixed. If you are able to compile code from source you can clone the BA3 repository which has been updated. I will create an updated release as well but it may take me a few days.

**Comment by dorseyb** [comment]
Thanks for the quick fix! I will compile it on Monday and give it a go.
Brian D.
________________________________

**Comment by brannala** [comment]
You're welcome. I will close this issue now, but let me know if you have any troubles with the new version.
