### ISSUE TITLE
ask help for BA3 compling

### ISSUE THREAD

**Issue by wangshuli174** [brannala/BA3#4]
Dr. Bruce Rannala, 

       Sorry to disturb you. My name is Shuli Wang, i am a graduate student learning botany in Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences.  I am studying BA3 for genetic analysis these days. According to your suggestions, i used MSYS to compile BA3 source code files, but there are always errors after the command "make".  The makefile edited and errors picture are attached in this email, please help me find the reasons. Thank you very much for your time and help.

       Best wishes,

         Shuli Wang
makefile
INCLUDE = -Iinclude
CFLAGS = -O3
LDLIBS = -lgsl
CC = g++
all:
	$(CC) $(CFLAGS) src/main.cpp $(INCLUDE) $(LDLIBS) -o BA3_x64
error
![errors](https://user-images.githubusercontent.com/66584587/83993323-a9a30880-a985-11ea-9191-bb2b8b278483.png)

**Comment by brannala** [comment]
Hi Shuli,
You are missing a compiler flag in your makefile that specifies 
whether the program is compiled for SNP data or 
microsatellites. For example, if you have the gsl library 
installed in the standard locations and the files BA3.h and 
main.cpp are in the current directory you can compile a version 
for SNPs using the command:

g++ --static -O1 -DSNP main.cpp -o BA3 -lgsl

The flag for microsatellites is:

-DMSAT

Bruce

wangshuli174 writes:

> Dr. Bruce Rannala, 
>
>        Sorry to disturb you. My name is Shuli Wang, i am a 
>        graduate student learning botany in Xishuangbanna 
>        Tropical Botanical Garden, Chinese Academy of Sciences. 
>        I am studying BA3 for genetic analysis these 
>        days. According to your suggestions, i used MSYS to 
>        compile BA3 source code files, but there are always 
>        errors after the command "make".  The makefile edited and 
>        errors picture are attached in this email, please help me 
>        find the reasons. Thank you very much for your time and 
>        help.
>
>        Best wishes,
>
>          Shuli Wang
> makefile
> INCLUDE = -Iinclude
> CFLAGS = -O3
> LDLIBS = -lgsl
> CC = g++
> all:
> 	$(CC) $(CFLAGS) src/main.cpp $(INCLUDE) $(LDLIBS) -o 
> BA3_x64
> error
> ![errors](https://user-images.githubusercontent.com/66584587/83993323-a9a30880-a985-11ea-9191-bb2b8b278483.png)


-- 
Bruce Rannala
Professor, Evolution & Ecology, UC Davis
