### ISSUE TITLE
Low ESS for logprob in trace file

### ISSUE THREAD

**Issue by Dieggarp** [brannala/BA3#7]
Hi Bruce,
I am writing you because in all my several runs I found low ESS values for logprob. I am running Bayesass for 5 populations of ~10 individuals using 4k SNPs. I tried with different numbers of iterations (1m - 10m) and even when the rest of the parameters have more than 5k ESS, the logprob continue being too small (< 20). I attach the trace file and could attach the input if you needed. 
[4k.5g.trace.txt](https://github.com/brannala/BA3/files/7186915/4k.5g.trace.txt)

**Comment by brannala** [comment]
Hi Diego,
logProb is the joint prior probability of the model -- it is not 
something you should worry about. You should look for consistency 
of parameter estimates across runs with different seeds.
Best wishes,
Bruce


Diego writes:

> Hi Bruce,
> I am writing you because in all my several runs I found low ESS 
> values for logprob. I am running Bayesass for 5 populations of 
> ~10 individuals using 4k SNPs. I tried with different numbers of 
> iterations (1m - 10m) and even when the rest of the parameters 
> have more than 5k ESS, the logprob continue being too small (< 
> 20). I attach the trace file and could attach the input if you 
> needed. 
> [4k.5g.trace.txt](https://github.com/brannala/BA3/files/7186915/4k.5g.trace.txt)


-- 
Bruce Rannala
Professor, Evolution & Ecology, UC Davis
